server:
  port: 8898
spring:
  application:
    name: hadoop-demo
  datasource:
    hive: #hive数据源
      url: jdbc:hive2://192.168.134.11:10000/tdm
      type: com.alibaba.druid.pool.DruidDataSource
      username: etl
      password: etl
      driver-class-name: org.apache.hive.jdbc.HiveDriver
    common-config: #连接池统一配置，应用到所有的数据源
      initialSize: 1
      minIdle: 1
      maxIdle: 5
      maxActive: 50
      maxWait: 10000
      timeBetweenEvictionRunsMillis: 10000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      filters: stat
hdfs:
  hdfsPath: hdfs://node1:8020
  hdfsName: etl

oozie:
  url: http://node1:11000/oozie
  wf:
    application:
      path: hdfs://node1:9000/user/oozie/workflow/hiveserver2.xml
  use:
    system:
      libpath: true
  libpath: hdfs://node1:8020/user/oozie/share/lib
  callback:
    url: http://172.16.120.29:8080/label/oozie/callback?executeType=$1\&taskType=$2\&callbackId=$3
  jdbc:
    url: jdbc:hive2://node1:10000/default
    password:
  nameNode: hdfs://node1:8020
  resourceManager: hdfs://node1:8088
  queueName: default
  job-tracker: node1:8032
